### PR TITLE
Fix getTotalTimeOfEntry calculation with missing _blocked_queueing

### LINKED ISSUE #67: Waterfall view fails when _blocked_queueing is undefined
image

The function `getTotalTimeOfEntry` is treating the `_blocked_queueing` as required, while it's not part of the spec ([1](http://www.softwareishard.com/blog/har-12-spec/#timings) or [2](https://github.com/ahmadnassri/har-spec/blob/master/versions/1.2.md#timings)).

I'm extracting the har from messages through a cdpSession, and this field is missing.

I think it should default the value to 0 if it doesn't exist.
Right now it creates SVGs with NaN attributes.

### PR DESCRIPTION
**Pull request by omril1**
Fixes #67

### CODE REVIEW

**Comment by omril1** [comment]
👋 Is anything missing?

**Comment by christian-bromann** [comment]
@farhan-sauce can you take a look?

**Review by farhan-sauce — APPROVED** [review]
LGTM 👍

**Comment by christian-bromann** [comment]
retriggered pipeline

**Comment by christian-bromann** [comment]
Seems that the trigger doesn't work, will fix it.

**Pull request merged**
