### PR TITLE
fix: Use alternate flexboxgrid component for react

### LINKED ISSUE #106: Global CSS cannot be imported from within node_modules.
### Bug report

I'm using Next.js and I can't import a CSS file from a node_modules 3rd party library.

Terminal error: 

```
./node_modules/flexboxgrid2/flexboxgrid2.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-flexbox-grid/lib/classNames.js
```

### PR DESCRIPTION
**Pull request by sridhareaswaran**
Replace 'react-flexbox-grid' with 'react-styled-flexboxgrid' that doesn't require direct import of css from node_modules.

Fixes #106

### CODE REVIEW

**Comment by sridhareaswaran** [comment]
@farhan687 @paweldudzinski  Tested with the example project set in the repo. Kindly review.

Thanks!

**Comment by paweldudzinski** [comment]
@sridhareaswaran tests are failing

**Comment by sridhareaswaran** [comment]
Hi @paweldudzinski the test snapshots are updated and are passing on my local. Kindly verify.

**Comment by sridhareaswaran** [comment]
Hi, @paweldudzinski can you please trigger the test workflow? Also, can we set the test workflow to trigger automatically upon PR?

**Comment by paweldudzinski** [comment]
@sridhareaswaran fix was published.

**Pull request merged**
